// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "michaelmoritz.io",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://michaelmoritz.io.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
